"""Constants for the Ecobulles integration."""

DOMAIN = "ecobulles"
CONF_ENABLE_RAW_CO2_SENSOR = "enable_raw_co2_sensor"
CONF_CO2_BOTTLE_WEIGHT_KG = "co2_bottle_weight"
CONF_CO2_MICROMETRIC_SCREW_SETTING = "co2_micrometric_screw_setting"
CONF_CO2_PRESSURE_BAR = "co2_pressure_bar"
CONF_CO2_MIN_DOSE_MG_PER_L = "co2_min_dose_mg_per_l"
CONF_CO2_MAX_DOSE_MG_PER_L = "co2_max_dose_mg_per_l"
CONF_CO2_REFERENCE_PULSE_MS_PER_L = "co2_reference_pulse_ms_per_l"
